### ISSUE TITLE
Merge upstream changes from ASM 5.2, 6.0-BETA

### ISSUE THREAD

**Issue by retronym** [scala/scala-asm-legacy#13]
@forax suggested that the ASM 5.2 would be worthwhile for us as it contains a few bug fixes: http://asm.ow2.org/history.html

ASM 6.0 is almost [almost ready](https://mail.ow2.org/wws/arc/asm/2017-07/msg00002.html) too. We might instead jump straight to that, which will give us the platform to read/write `module-info.class`, although we might not actually need this. It also contains the equivalent of my patch in #12.

Finally, ASM has moved to [Git](https://gitlab.ow2.org/asm/), so we should update (and simplify!) our process for pulling from upstream. We can either merge from the upstream tag, or create a new branch with our changes rebased on the upstream tag.

**Comment by lrytz** [comment]
I'll do this for 2.12.4

**Comment by lrytz** [comment]
I created a fork of the new asm git repo here https://github.com/scala/asm

Not entirely sure yet how to deal with updates. I think having a branch into which we merge changes from upstream is not realistic with the current setup, because
  - our fork has the source files moved to a different package / directory
  - our fork has removed files that are in the original repo, including some sources files

This would cause many merge conflicts.

Another reason I don't like merging in changes is that it makes it harder to keep track of our own patches. If re-apply our patches on top of their tags each time we upgrade, we can easily see the differences in the git log, and we can also clean up / squash our patches over time.

My current plan: create a new branch each time we start off a new ASM release tag, then re-apply all our changes from the previous branch. Create more scripts to simplify that process.

**Comment by lrytz** [comment]
I created a branch https://github.com/scala/scala-asm/commits/s-5.1 with all patches from this legacy repo. Pushed a tag in the new repo (https://github.com/scala/scala-asm/releases/tag/v5.1.0-scala-2), which triggered a release. I downloaded the jar from sonatype staging and compared with the one from maven that was released with the legacy repo, they are identical up to a properties file.

**Comment by lrytz** [comment]
Instructions to upgrade asm in the new repository: https://github.com/scala/scala-asm/blob/readme/README.md

I just did it for 5.2, the process takes ~30 minutes now.

However there seems to be a problem with the artifacts, there are errors when trying to close the repository: 
![image](https://user-images.githubusercontent.com/119636/30440688-96e2ae4c-9977-11e7-96b8-2ea4235a320c.png)

I'll check that later.

**Comment by lrytz** [comment]
OK, added the key, now closing the repository worked (https://oss.sonatype.org/content/repositories/orgscala-lang-1443/). I'll try it out later.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6084
